local MiniColors = require('mini.colors')

-- Define colors using the same palette as the original lush theme
local black = '#262B31'
local white = '#EBEBEB'
local grey = '#787878'
local lightgrey = '#D1D1D1'
local accent = '#EE473F'
local green = '#BBFF99'
local red = '#FF9999'

local groups = {
  ['@attribute'] = { link = 'Macro' },
  ['@attribute.builtin'] = { link = 'Special' },
  ['@boolean'] = { link = 'Boolean' },
  ['@character'] = { link = 'Character' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@comment'] = { link = 'Comment' },
  ['@comment.error'] = { link = 'DiagnosticError' },
  ['@comment.note'] = { link = 'DiagnosticInfo' },
  ['@comment.todo'] = { link = 'Todo' },
  ['@comment.warning'] = { link = 'DiagnosticWarn' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Special' },
  ['@constructor'] = { link = 'Special' },
  ['@diff'] = {},
  ['@diff.delta'] = { link = 'Changed' },
  ['@diff.minus'] = { link = 'Removed' },
  ['@diff.plus'] = { link = 'Added' },
  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'Special' },
  ['@keyword'] = { link = 'Keyword' },
  ['@label'] = { link = 'Label' },
  ['@lsp'] = {},
  ['@lsp.mod.deprecated'] = { link = 'DiagnosticDeprecated' },
  ['@lsp.type.class'] = { link = '@type' },
  ['@lsp.type.comment'] = { link = '@comment' },
  ['@lsp.type.decorator'] = { link = '@attribute' },
  ['@lsp.type.enum'] = { link = '@type' },
  ['@lsp.type.enumMember'] = { link = '@constant' },
  ['@lsp.type.event'] = { link = '@type' },
  ['@lsp.type.function'] = { link = '@function' },
  ['@lsp.type.interface'] = { link = '@type' },
  ['@lsp.type.keyword'] = { link = '@keyword' },
  ['@lsp.type.macro'] = { link = '@constant.macro' },
  ['@lsp.type.method'] = { link = '@function.method' },
  ['@lsp.type.modifier'] = { link = '@type.qualifier' },
  ['@lsp.type.namespace'] = { link = '@module' },
  ['@lsp.type.number'] = { link = '@number' },
  ['@lsp.type.operator'] = { link = '@operator' },
  ['@lsp.type.parameter'] = { link = '@variable.parameter' },
  ['@lsp.type.property'] = { link = '@property' },
  ['@lsp.type.regexp'] = { link = '@string.regexp' },
  ['@lsp.type.string'] = { link = '@string' },
  ['@lsp.type.struct'] = { link = '@type' },
  ['@lsp.type.type'] = { link = '@type' },
  ['@lsp.type.typeParameter'] = { link = '@type.definition' },
  ['@lsp.type.variable'] = { link = '@variable' },
  ['@markup'] = { link = 'Special' },
  ['@markup.heading'] = { link = 'Title' },
  ['@markup.heading.1.delimiter.vimdoc'] = { bg = white, fg = white, nocombine = true, sp = black, underdouble = true },
  ['@markup.heading.2.delimiter.vimdoc'] = { bg = white, fg = white, nocombine = true, sp = black, underline = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.link'] = { link = 'Underlined' },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.underline'] = { underline = true },
  ['@module'] = { link = 'Structure' },
  ['@module.builtin'] = { link = 'Special' },
  ['@number'] = { link = 'Number' },
  ['@number.float'] = { link = 'Float' },
  ['@operator'] = { link = 'Operator' },
  ['@property'] = { link = 'Identifier' },
  ['@punctuation'] = { link = 'Delimiter' },
  ['@punctuation.special'] = { link = 'Special' },
  ['@spell'] = {},
  ['@string'] = { link = 'String' },
  ['@string.escape'] = { link = '@string.special' },
  ['@string.regexp'] = { link = '@string.special' },
  ['@string.special'] = { link = 'SpecialChar' },
  ['@string.special.url'] = { link = 'Underlined' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.builtin'] = { link = 'Special' },
  ['@text'] = {},
  ['@text.diff.add'] = { link = 'DiffAdd' },
  ['@text.diff.delete'] = { link = 'DiffDelete' },
  ['@text.note'] = { link = 'Todo' },
  ['@text.todo'] = { link = 'Todo' },
  ['@type'] = { link = 'Type' },
  ['@type.builtin'] = { link = 'Special' },
  ['@variable'] = { fg = black },
  ['@variable.builtin'] = { link = 'Special' },
  ['@variable.parameter.builtin'] = { link = 'Special' },
  ALEError = { link = 'DiagnosticError' },
  ALEErrorSign = { link = 'ALEError' },
  ALEInfo = { link = 'DiagnosticInfo' },
  ALEInfoSign = { link = 'ALEInfo' },
  ALEWarning = { link = 'DiagnosticWarn' },
  ALEWarningSign = { link = 'ALEWarning' },
  -- TODO(stefanvanburen): revisit this
  -- Added = { ctermfg = 2, fg = '#005523' },
  Bold = { bold = true },
  Boolean = { link = 'Constant' },
  -- TODO(stefanvanburen): revisit this
  -- Changed = { ctermfg = 6, fg = '#007373' },
  Character = { link = 'Constant' },
  ColorColumn = { bg = lightgrey },
  Comment = { fg = grey },
  ComplMatchIns = {},
  Conceal = {},
  Conditional = { link = 'Statement' },
  Constant = { fg = black },
  -- TODO(stefanvanburen): revisit this
  -- CurSearch = { bg = '#6b5300', ctermbg = 3, ctermfg = 15, fg = '#eef1f8' },
  Cursor = {},
  CursorColumn = {},
  CursorIM = {},
  CursorLine = { bg = lightgrey },
  CursorLineFold = { link = 'FoldColumn' },
  CursorLineNr = {},
  CursorLineSign = { link = 'SignColumn' },
  Debug = { link = 'Special' },
  Define = { link = 'PreProc' },
  Delimiter = { fg = black },
  -- TODO(stefanvanburen): revisit this
  -- DiagnosticDeprecated = { sp = '#590008', strikethrough = true },
  DiagnosticError = { fg = accent },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticHint = { fg = grey },
  DiagnosticInfo = { fg = grey },
  -- TODO(stefanvanburen): revisit this
  -- DiagnosticOk = { ctermfg = 2, fg = '#005523' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  -- TODO(stefanvanburen): revisit this
  -- DiagnosticUnderlineError = { sp = '#590008', underline = true },
  -- DiagnosticUnderlineHint = { sp = '#004c73', underline = true },
  -- DiagnosticUnderlineInfo = { sp = '#007373', underline = true },
  -- DiagnosticUnderlineOk = { sp = '#005523', underline = true },
  -- DiagnosticUnderlineWarn = { sp = '#6b5300', underline = true },
  DiagnosticUnnecessary = { link = 'Comment' },
  DiagnosticVirtualLinesError = { link = 'DiagnosticError' },
  DiagnosticVirtualLinesHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualLinesInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualLinesOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualLinesWarn = { link = 'DiagnosticWarn' },
  DiagnosticVirtualTextError = { link = 'DiagnosticError' },
  DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
  DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
  DiagnosticWarn = { fg = accent },
  DiffAdd = { fg = black, bg = green },
  DiffChange = {},
  DiffDelete = { fg = black, bg = red },
  DiffText = { fg = white, bg = accent, bold = true },
  Directory = {},
  EndOfBuffer = { link = 'NonText' },
  Error = { fg = white, bg = accent, bold = true },
  ErrorMsg = {},
  Exception = { link = 'Statement' },
  ExtraWhitespace = { link = 'WarningMsg' },
  Float = { link = 'Number' },
  FloatBorder = { link = 'NormalFloat' },
  FloatFooter = { link = 'FloatTitle' },
  -- TODO(stefanvanburen): revisit this
  -- FloatShadow = { bg = '#9b9ea4', blend = 80, ctermbg = 0 },
  -- FloatShadowThrough = { bg = '#9b9ea4', blend = 100, ctermbg = 0 },
  FloatTitle = { link = 'Title' },
  FoldColumn = {},
  Folded = {},
  -- TODO(stefanvanburen): revisit this
  -- Function = { ctermfg = 6, fg = '#007373' },
  Identifier = { fg = black },
  Ignore = { link = 'Normal' },
  IncSearch = { fg = white, bg = accent, bold = true },
  Include = { link = 'PreProc' },
  Italic = { italic = true },
  Keyword = { link = 'Statement' },
  Label = { link = 'Statement' },
  LineNr = {},
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  LspCodeLens = { link = 'NonText' },
  LspCodeLensSeparator = { link = 'LspCodeLens' },
  LspInlayHint = { link = 'NonText' },
  LspReferenceRead = { link = 'LspReferenceText' },
  LspReferenceTarget = { link = 'LspReferenceText' },
  LspReferenceText = { bg = lightgrey },
  LspReferenceWrite = { link = 'LspReferenceText' },
  LspSignatureActiveParameter = { link = 'Visual' },
  Macro = { link = 'PreProc' },
  MasonError = { fg = accent },
  MasonHeader = { bold = true },
  MasonHeaderSecondary = { fg = grey },
  MasonHeading = { bold = true },
  MasonHighlight = { fg = accent },
  MasonHighlightBlock = { bg = accent, fg = white },
  MasonHighlightBlockBold = { bg = accent, bold = true, fg = white },
  -- TODO(stefanvanburen): revisit this
  -- MasonHighlightBlockBoldSecondary = { bg = '#d85b55', bold = true, fg = white },
  -- MasonHighlightBlockSecondary = { bg = '#d85b55', fg = white },
  -- MasonHighlightSecondary = { fg = '#d85b55' },
  MasonLink = { link = 'Underlined' },
  MasonMuted = { fg = grey },
  MasonMutedBlock = { bg = lightgrey, fg = black },
  MasonMutedBlockBold = { bg = lightgrey, bold = true, fg = black },
  MasonNormal = { link = 'NormalFloat' },
  MatchBackground = { link = 'ColorColumn' },
  MatchParen = { fg = accent, bg = white },
  MatchParenCur = { link = 'MatchParen' },
  MatchWord = { link = 'MatchParen' },
  MiniCompletionActiveParameter = { link = 'LspSignatureActiveParameter' },
  MiniCompletionInfoBorderOutdated = { link = 'DiagnosticFloatingWarn' },
  MiniDepsChangeAdded = { link = 'Added' },
  MiniDepsChangeRemoved = { link = 'Removed' },
  MiniDepsHint = { link = 'DiagnosticHint' },
  MiniDepsInfo = { link = 'DiagnosticInfo' },
  MiniDepsMsgBreaking = { link = 'DiagnosticWarn' },
  MiniDepsPlaceholder = { link = 'Comment' },
  MiniDepsTitle = { link = 'Title' },
  MiniDepsTitleError = { link = 'DiffDelete' },
  MiniDepsTitleSame = { link = 'DiffText' },
  MiniDepsTitleUpdate = { link = 'DiffAdd' },
  MiniDiffOverAdd = { link = 'DiffAdd' },
  MiniDiffOverChange = { link = 'DiffText' },
  MiniDiffOverChangeBuf = { link = 'MiniDiffOverChange' },
  MiniDiffOverContext = { link = 'DiffChange' },
  MiniDiffOverContextBuf = {},
  MiniDiffOverDelete = { link = 'DiffDelete' },
  MiniDiffSignAdd = { link = 'Added' },
  MiniDiffSignChange = { link = 'Changed' },
  MiniDiffSignDelete = { link = 'Removed' },
  MiniFilesBorder = { link = 'FloatBorder' },
  MiniFilesBorderModified = { link = 'DiagnosticFloatingWarn' },
  MiniFilesCursorLine = { link = 'CursorLine' },
  MiniFilesDirectory = { link = 'Directory' },
  MiniFilesFile = {},
  MiniFilesNormal = { link = 'NormalFloat' },
  MiniFilesTitle = { link = 'FloatTitle' },
  MiniFilesTitleFocused = { link = 'FloatTitle' },
  MiniTrailspace = { link = 'WarningMsg' },
  ModeMsg = {},
  MoreMsg = {},
  MsgArea = {},
  MsgSeparator = {},
  NonText = { fg = grey },
  Normal = { fg = black, bg = white },
  NormalFloat = { fg = black, bg = lightgrey },
  NormalNC = {},
  Number = { link = 'Constant' },
  Operator = { fg = black },
  Pmenu = { fg = black, bg = lightgrey },
  PmenuExtra = { link = 'Pmenu' },
  PmenuExtraSel = { link = 'PmenuSel' },
  PmenuKind = { link = 'Pmenu' },
  PmenuKindSel = { link = 'PmenuSel' },
  PmenuMatch = { bold = true },
  PmenuMatchSel = { bold = true },
  PmenuSbar = { bg = lightgrey },
  PmenuSel = { fg = white, bg = accent, bold = true },
  PmenuThumb = {},
  PreCondit = { link = 'PreProc' },
  PreProc = { fg = black },
  Question = {},
  QuickFixLine = {},
  -- TODO(stefanvanburen): revisit this
  -- RedrawDebugClear = { bg = '#fce094', ctermbg = 3, ctermfg = 15 },
  -- RedrawDebugComposed = { bg = '#b3f6c0', ctermbg = 2, ctermfg = 15 },
  -- RedrawDebugNormal = { reverse = true },
  -- RedrawDebugRecompose = { bg = '#ffc0b9', ctermbg = 1, ctermfg = 15 },
  -- TODO(stefanvanburen): revisit this
  -- Removed = { ctermfg = 1, fg = '#590008' },
  Repeat = { link = 'Statement' },
  Search = { fg = white, bg = accent, bold = true },
  SignColumn = { fg = black, bg = white },
  SnippetTabstop = { link = 'Visual' },
  Special = { fg = black },
  SpecialChar = { link = 'Special' },
  SpecialComment = { link = 'Special' },
  SpecialKey = {},
  SpellBad = { fg = accent, bg = white, undercurl = true },
  SpellCap = {},
  SpellLocal = {},
  SpellRare = {},
  Statement = { fg = black, bold = true },
  StatusLine = { fg = white, bg = black },
  StatusLineNC = { fg = black, bg = lightgrey },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  StorageClass = { link = 'Type' },
  -- TODO(stefanvanburen): revisit this
  -- String = { ctermfg = 2, fg = '#005523' },
  Structure = { link = 'Type' },
  Substitute = { fg = white, bg = black },
  TabLine = {},
  TabLineFill = {},
  TabLineSel = { fg = white, bg = black },
  Tag = { link = 'Special' },
  TermCursor = {},
  TermCursorNC = {},
  Title = {},
  Todo = { fg = accent, bold = true },
  Type = { fg = black },
  Typedef = { link = 'Type' },
  Underlined = { underline = true },
  VertSplit = {},
  Visual = { fg = white, bg = black },
  WarningMsg = { fg = accent },
  Whitespace = { link = 'NonText' },
  WildMenu = { fg = white, bg = black },
  -- TODO(stefanvanburen): revisit this
  -- WinBar = { bg = '#eef1f8', bold = true, fg = '#4f5258' },
  -- WinBarNC = { bg = '#eef1f8', fg = '#4f5258' },
  WinSeparator = { link = 'Normal' },
  diffAdded = { link = 'DiffAdd' },
  diffRemoved = { link = 'DiffDelete' },
  gitcommitOverflow = { link = 'WarningMsg' },
}

local terminal = {
  [0] = black,
  [1] = accent,
  [2] = '#005523',
  [3] = '#6b5300',
  [4] = '#004c73',
  [5] = '#007373',
  [6] = '#007373',
  [7] = lightgrey,
  [8] = '#9b9ea4',
  [9] = accent,
  [10] = '#005523',
  [11] = '#6b5300',
  [12] = '#004c73',
  [13] = '#590008',
  [14] = '#007373',
  [15] = white,
}

return MiniColors.as_colorscheme({
  name = 'rams',
  groups = groups,
  terminal = terminal,
})
